### PR TITLE
Add options object and feature providers, with preloaded provider

### PR DESCRIPTION
**Pull request by magwo**
Also expose createPreloadedFeatureProvider to give API users full control over when the preloading is done, as it can take a few seconds and is sync.
A future PR might consider doing the preloading with async file operations which should make it much faster.

Object size approximations indicate that the fully preloaded timezone features object uses about 140 MB of memory. Might be somewhat more in practice due to overheads.

### CODE REVIEW

**Comment by magwo** [comment]
What do you think about this API design?

It is flexible but might be confusing to API users. I'm considering something simpler, for example exposing a function called `preloadFeatures` which will swap out the on demand provider to a preloaded one. I think it is important to at least give API users control over _when_ the preloading is done, as it is quite time consuming.

**Comment by magwo** [comment]
A big downside of exposing a `preloadFeatures` is that it introduces global state which complicates testing. For example, how do we correctness test the on demand loading, if the preload was done in a previous test?

**Comment by evansiroky** [comment]
Thanks a bunch for this PR.  I'm currently at a conference, but will look at this on Thursday.  Sorry for the delay.

**Comment by evansiroky** [comment]
This PR looks great!  Thanks a bunch.  Just one request, please add some documentation to the README.  :)

**Comment by magwo** [comment]
Ok! Will do soon.

**Comment by magwo** [comment]
@evansiroky Docs added.

**Comment by magwo** [comment]
By the way, I implemented a version with polyline encoded in-memory storage. The memory usage went from 900 MB to 720 MB or something. So I don't think it's worth the hassle, added code, complexity and potential brittleness. It will probably also affect performance slightly negatively.

In the end the memory saving is not enough. I think the very large number of objects in the quad tree is what's causing most of the memory usage. It would be interesting to explore other optimisation options.

**Comment by evansiroky** [comment]
Awesome!  Looks great.  I'm going to do some work on fixing this failing test case this weekend and will merge when that is complete.  

Thanks for taking the time to investigate the polyline encoding.  It's a bummer that the memory savings were not that great, but good to know.

Feel free to make another PR if you come up with a better optimization than the quad tree.

**Comment by magwo** [comment]
I just had a pretty weird but maybe powerful idea..

Consider extending the preloaded feature provider object so that you can tell which timezones you wish to keep in memory. Many products operate on a one or a few specific timezones. I suspect many users may want good performance on specific regions, while not paying 900 MB of memory, but still having the capability to look up timezone of "unexpected" regions.

```javascript
geoTz.createPreloadedFeatureProvider(["America/*", "Europe/Stockholm, "Europe/Berlin"])
```

**Comment by evansiroky** [comment]
I also had an idea along those lines.  As features are looked up, they could get stored in memory for later use.  Perhaps even more advanced would be to set a timeout of removing these features from memory if they aren't accessed for a certain amount of time.

The update script is set to index this geographic data up to a certain percentage of the area of the world.  In the latest generated data this works out to grids of dimensions 2.8125 longitude degrees by 1.40625 latitude degrees.  Shown below is Europe.  See [this jsfiddle](http://jsfiddle.net/4a87k/764/) for an interactive map.

screen shot 2017-02-09 at 1 32 02 pm

I haven't tested a lot of real-world queries but agree as you do that each application will probably be more specific to particular areas.

**Comment by magwo** [comment]
Yeah you're basically talking about a [LRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_Recently_Used_.28LRU.29) cache.

Which should work well, maybe even using a library for it for nice and bug-free features.

**Comment by evansiroky** [comment]
I merged this into a development branch because I also want to update the turf packages to their new namespace.

**Pull request merged**
